name: Code Coverage

on: [pull_request]

jobs:
  test_and_coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v4.2.1
        with:
          ref: ${{ github.base_ref }}
          
      - name: Use Node.js v20.x
        uses: actions/setup-node@v4.0.4
        with:
          node-version: v20.x

      - name: Set up Xvfb
        run: |
          sudo apt-get install -y xvfb
          Xvfb :99 -ac &
          export DISPLAY=:99

      - name: Install dependencies
        run: npm ci

      - name: Run test coverage
        run: npm test

      - name: Code Coverage Summary Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: 'coverage/coverage-cobertura.xml'
          badge: true
          format: 'markdown'
          output: 'both'

      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2.9.0
        if: github.event_name == 'pull_request'
        with:
          recreate: true
          path: code-coverage-results.md

      - name: Write to Job Summary
        run: cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY
